New "material" theme
pxlsspace/Pxls pull request #400
Opened 2020-07-30 17:39 UTC by FeeeeK

2020-08-02 02:50 UTC, BlankParenthesis commented on resources/public/pxls.js
> +        const genCheckboxGroup = (label, id) => {
Many of the changes in the PR stem from this change. It changes the current hierarchy of nodes from having the input contained within the label, to having the input precede the label and reference it with the `for` attribute. Both of these are valid ways to associate a label with an input, as mentioned in the [MDN article on the label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).

When doing a recent restructure of the HTML in the settings panel, I chose to keep the current method of having the input be a child of the label. My reasoning was that it was more flexible as unique ids need not be generated for every input and also happened to be the existing system, with no need for change besides preference.

That said, I would request that the development team come to a conclusion on which form the project wants to use from now on and stick to it before merging this PR.

2020-10-08 23:19 UTC, netux requested changes
Team looks stylish but needs some changes and bug fixes.

2020-10-08 23:19 UTC, netux commented on resources/public/pxls.js
> +        }).trigger('input');
Since this triggers _all_ input handlers it causes and obscure bug where the view won't be set on the center of the canvas when the page is loaded without any query arguments on the URL.

From my debugging:
- The page is centered inside [`board.start()`](https://github.com/pxlsspace/Pxls/blob/ddb590a9c9a5dc9d1de24f4be7c500f0bb2fdb23/resources/public/pxls.js#L1549), where it gets the coordinates by doing `query.get('x') || self.width / 2` and `query.get('y') || self.height / 2`. This depends on query parameters not being initialized yet (thus `query.get('x')` and `query.get('x')` would return undefined)
- This trigger to all input event handlers
  1. triggers the event handler for [template opacity slider, which calls `template.update()`](https://github.com/pxlsspace/Pxls/blob/ddb590a9c9a5dc9d1de24f4be7c500f0bb2fdb23/resources/public/pxls.js#L2429)
  2. [which calls `board.update()`, where the query is updated with values that default to 0](https://github.com/pxlsspace/Pxls/blob/ddb590a9c9a5dc9d1de24f4be7c500f0bb2fdb23/resources/public/pxls.js#L1617)
  3. thus setting the query x and y to 0 before they are presumed to be undefined.

There are multiple points in which this can be fixed, but maybe the one that touches less parts of the old code is to only run the new event handler that updates the color of the input bar manually instead of triggering all input handlers.

2020-10-08 23:19 UTC, netux commented on resources/public/pxls.js
> +        const genCheckboxGroup = (label, id) => {
Either style is okay for me, but I'd rather keep it consistent and nest the input inside the label like how it was before.
Is there a way to re-implement the new visuals that way?

2020-10-08 23:19 UTC, netux commented on resources/public/pxls.js
> +          const lbl = crel('label', { for: id, class: 'input-group' },
Adding to the thing above, this element is even inconsistent with the one on the settings panel, and causes a bug where the new checkbox doesn't display for chat settings.
![image](https://user-images.githubusercontent.com/6181929/95522566-caff1a00-09a2-11eb-8b5a-e915fe13a425.png)

2020-10-08 23:19 UTC, netux commented on resources/public/themes/matte.css
> +    -webkit-appearance: none;
On Firefox this has the effect of hiding the dropdown arrow to the right of `<select>`s.
![image](https://user-images.githubusercontent.com/6181929/95522762-57a9d800-09a3-11eb-85c7-e70a9ab15a06.png)
This made it harder for me to identify what the thing was. Please consider removing this rule.
![image](https://user-images.githubusercontent.com/6181929/95522769-5e384f80-09a3-11eb-89c4-51acbcd0a8d2.png)

2020-10-26 14:16 UTC, BlankParenthesis commented on resources/public/pxls.js
> +        $(select).click(function () { $(this).toggleClass('select-arrow'); });
This is insufficient to keep track of the `select`'s  state.
As an example, a user could click on the select to open the dropdown, then click elsewhere on the page to close it.
This leaves the arrow in the wrong orientation.

One alternative is instead binding the arrow the the `:focus` selector in CSS, though that too has some state issues - albeit probably fewer and ones less persistent.

2020-10-26 17:24 UTC, netux requested changes

2020-10-26 17:24 UTC, netux commented on resources/public/themes/matte.css
> +# "Matte" theme by github.com/feeeek
This is not how you add comments in CSS. I'm guessing you meant
```css
/* # "Matte" theme by github.com/feeeek */
```

This is the cause of your theme's colors breaking.
![image](https://user-images.githubusercontent.com/6181929/97205716-94910f80-1796-11eb-8b18-60b1c6056239.png)

With that fixed:
![image](https://user-images.githubusercontent.com/6181929/97205766-a4a8ef00-1796-11eb-959d-300c69a4cf1c.png)

2020-10-26 17:24 UTC, netux commented on resources/public/pxls.js
> +        $(select).click(function () { $(this).toggleClass('select-arrow'); });
I agree with Blank, but I'd suggest just leaving the arrow pointing down all the time for now.

2020-10-26 17:27 UTC, netux commented
Your "Fix merge conflicts" commit didn't merge all the changes from master to this branch.
For example, the commit updates index.html to load pxlsMarkdown.js instead of anchorme, but pxls.js still references anchorme (which breaks chat).

Please correctly merge master into this branch.

2020-10-26 23:49 UTC, netux approved these changes

2020-10-27 20:54 UTC, netux requested changes

2020-10-27 20:54 UTC, netux commented on resources/public/pxls.js
> +        self.prettifySelect('select');
You forgot to remove this.

2020-10-28 18:43 UTC, netux approved these changes

2020-10-29 23:14 UTC, merged