Shadow-Banned Chat Messages
pxlsspace/Pxls pull request #472
Opened 2021-02-06 15:57 UTC by FlyingSixtySix

### Goals

This pull request aims to hide new and historical chat messages by shadow-banned users from users without the `chat.history.shadowbanned` and `user.receivestaffbroadcasts` permissions, for history and new messages respectively.  Users with said permissions will see those messages as `.9em`-sized `#F66`-colored text.

### Specifics

- For shadow-banned users, their messages will be processed but not be re-broadcast.  It will be sent back to give the illusion that the message was handled like normal.
- For users without the permissions, no packets will be received regarding new messages from shadow-banned users.
- For users with the permission, messages will have the `data-shadow-banned` element attribute and appear as `.9em`-sized `#F66`-colored text.

### Screenshots

Perspective of a shadow-banned user:

<img src="https://files.f66.dev/uploads/firefox_JAr4fgAb9Y.png">

Perspective of a user with the necessary permissions:

<img src="https://files.f66.dev/uploads/firefox_1K9bE84nyk.png">

2021-02-06 17:55 UTC, netux requested changes
Looks good. I have some minor comments about it though.

2021-02-06 17:55 UTC, netux commented on src/main/java/space/pxls/server/PacketHandler.java
> +                server.broadcastSeparateForStaff(userPacket, staffPacket);
Maybe do this is if both `userPacket` and `staffPacket` aren't `null`?

2021-02-06 17:55 UTC, netux commented on src/main/java/space/pxls/data/Database.java
> +        return createChatMessage(author == null ? -1 : author.getId(), sent / 1000L, content, filtered, shadowBanned);
```suggestion
        return createChatMessage(author == null ? -1 : author.getId(), sent / 1000L, content, filtered, author == null ? false : author.isShadowBanned());
```
(and removing the `boolean shadowBanned` argument)

2021-02-06 17:55 UTC, netux commented on src/main/java/space/pxls/server/PacketHandler.java
> +        server.send(channel, new ServerChatHistory(App.getDatabase().getlastXMessagesForSocket(100, user.hasPermission("chat.history.purged"), user.hasPermission("chat.history.shadowbanned"), false))
When the shadow-banned user refreshes, they won't see their own messages.
This shouldn't be much of a problem considering the same happens for pixels on the canvas, but since we are actually storing the messages here its doable.

2021-02-06 17:55 UTC, netux commented on src/main/java/space/pxls/data/Database.java
> +    public List<ChatMessage> getlastXMessagesForSocket(int x, boolean includePurged, boolean includeShadowBanned, boolean ignoreFilter) {
Can we take this as a chance to fix that `l` in "Last" being lowercase? 😖

2021-02-06 18:27 UTC, FlyingSixtySix commented on src/main/java/space/pxls/server/PacketHandler.java
> +        server.send(channel, new ServerChatHistory(App.getDatabase().getlastXMessagesForSocket(100, user.hasPermission("chat.history.purged"), user.hasPermission("chat.history.shadowbanned"), false))
I was initially hoping this would get addressed in another pull request fixing the shadow-banned pixels issue, but given the opportunity I can take care of it here.  What would be the best way to pass in context regarding the requesting user's shadow-ban status?  If I pass in the `user` from `handleChatHistory`, that would knock out both permission check parameters, but looking right above I can see that `ServerChatbanState` takes three parameters, all of them being context from a `User` object.  If replacing the `includePurged` and `includeShadowBanned` parameters with a `User` is fine here, I'll tackle `ServerChatbanState` and whatever else uses the same style in another commit outside this pull request.

2021-02-06 19:06 UTC, netux commented on src/main/java/space/pxls/server/PacketHandler.java
> +        server.send(channel, new ServerChatHistory(App.getDatabase().getlastXMessagesForSocket(100, user.hasPermission("chat.history.purged"), user.hasPermission("chat.history.shadowbanned"), false))
🤔 how about always fetching shadow-banned messages, but filtering them out in `handleChatHistory`?
Otherwise you can add an `int requesterUserID` argument to `getLastXMessageForSocket` for which you always fetch their messages.

2021-02-06 19:07 UTC, netux commented on src/main/java/space/pxls/server/PacketHandler.java
> +        server.send(channel, new ServerChatHistory(App.getDatabase().getlastXMessagesForSocket(100, user.hasPermission("chat.history.purged"), user.hasPermission("chat.history.shadowbanned"), false))
If it's too complicated we can work on it in another PR.

2021-02-06 19:07 UTC, netux approved these changes

2021-02-06 19:17 UTC, FlyingSixtySix commented on src/main/java/space/pxls/server/PacketHandler.java
> +        server.send(channel, new ServerChatHistory(App.getDatabase().getlastXMessagesForSocket(100, user.hasPermission("chat.history.purged"), user.hasPermission("chat.history.shadowbanned"), false))
I'll tackle it in `handleChatHistory` - that seems most straight-forward.

2021-02-06 20:44 UTC, netux requested changes

2021-02-06 20:44 UTC, netux commented on src/main/java/space/pxls/server/PacketHandler.java
> +                .collect(Collectors.toList());
Forgot to filter out shadow banned messages depending on the `chat.history.shadowbanned` perm.

2021-02-06 21:20 UTC, FlyingSixtySix commented on src/main/java/space/pxls/server/PacketHandler.java
> +                .collect(Collectors.toList());
I tried thinking of a better way to filter it out based on permission, but c4bfc54 is all I could come up with.  If you have any suggestions on it, please let me know!

2021-02-07 01:33 UTC, FlyingSixtySix commented
Superseded by #472.

2021-02-07 01:33 UTC, closed without merging